/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Versao.Versao;
import Produto.Produto;
import Produto.ProdutoDAO;
import ProdutoPreco.ProdutoPreco;
import ProdutoPreco.ProdutoPrecoDAO;
import Util.Funcoes;
import Versao.VersaoDAO;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MIGRAÇÃO-PC
 */
public class TelaGerar extends javax.swing.JDialog {

    private List<Versao> listaVersao = new ArrayList<>();
    private List<Produto> listaProduto = new ArrayList<>();
    private List<ProdutoPreco> listaProdutoPreco = new ArrayList<>();

    /**
     * Creates new form TelaGerar
     */
    public TelaGerar(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        preencherJComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcb_versao = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jcb_icms = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LC PHARMA - GERAR TXT");
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gerar arquivo TXT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Versão do arquivo:");

        jcb_versao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Aliquota de ICMS:");

        jcb_icms.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12%", "17%", "17,5%", "18%", "19%", "20%", "21%", "22%", "17% (ALC)", "17,5% (ALC)", "18% (ALC)" }));

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/arrow_refresh.png"))); // NOI18N
        jButton1.setText("Gerar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/door_in.png"))); // NOI18N
        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcb_versao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 372, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jcb_icms, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcb_versao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcb_icms, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        gerarTXT();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    TelaGerar dialog = new TelaGerar(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaGerar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> jcb_icms;
    private javax.swing.JComboBox<String> jcb_versao;
    // End of variables declaration//GEN-END:variables

    private void preencherJComboBox() throws SQLException {
        listaVersao.clear();
        listaVersao = (ArrayList<Versao>) new VersaoDAO().listaVersao();

        for (Versao v : listaVersao) {
            jcb_versao.addItem("Versão: " + v.getVersao() + "  Referência: " + Funcoes.formataData(v.getData_vigencia(), "B", true));
        }

    }

    private boolean podeGerar() {
        if (jcb_versao.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Selecione uma versão para gerar o arquivo!");
            return false;
        } else {
            return true;
        }
    }

    private void gerar() throws Exception {
        if (podeGerar()) {
            File fileTXT = new File(".\\arquivo\\LC_PHARMA_" + jcb_icms.getSelectedItem() + ".txt");
            fileTXT.delete();

            FileWriter arq = new FileWriter(fileTXT, true);
            PrintWriter gravarArq = new PrintWriter(fileTXT, "ISO-8859-1");

            listaProduto.clear();
            listaProduto = (ArrayList<Produto>) new ProdutoDAO().listaProdutoBarras("%%");

            String escreva;
            double preco_venda = 0;
            double preco_custo = 0;
            double aliq_icms = 0;

            ProdutoPrecoDAO precoDao = new ProdutoPrecoDAO();

            for (Produto p : listaProduto) {
                ProdutoPreco prodPreco = precoDao.getProdutoPreco(p, listaVersao.get(jcb_versao.getSelectedIndex() - 1));
                if (prodPreco.getId_produto() > 0) {

                    if (p.getIcms_0().equals("Sim")) {
                        preco_custo = prodPreco.getPrecocusto_0();
                        preco_venda = prodPreco.getPrecovenda_0();
                        aliq_icms = 0;

                    } else if (jcb_icms.getSelectedItem().equals("12%")) {
                        preco_custo = prodPreco.getPrecocusto_12();
                        preco_venda = prodPreco.getPrecovenda_12();
                        aliq_icms = 12;

                    } else if (jcb_icms.getSelectedItem().equals("17%")) {
                        preco_custo = prodPreco.getPrecocusto_17();
                        preco_venda = prodPreco.getPrecovenda_17();
                        aliq_icms = 17;

                    } else if (jcb_icms.getSelectedItem().equals("17,5%")) {
                        preco_custo = prodPreco.getPrecocusto_17_5();
                        preco_venda = prodPreco.getPrecovenda_17_5();
                        aliq_icms = 17.5;

                    } else if (jcb_icms.getSelectedItem().equals("18%")) {
                        preco_custo = prodPreco.getPrecocusto_18();
                        preco_venda = prodPreco.getPrecovenda_18();
                        aliq_icms = 18;

                    } else if (jcb_icms.getSelectedItem().equals("19%")) {
                        preco_custo = prodPreco.getPrecocusto_19();
                        preco_venda = prodPreco.getPrecovenda_19();
                        aliq_icms = 19;

                    } else if (jcb_icms.getSelectedItem().equals("20%")) {
                        preco_custo = prodPreco.getPrecocusto_20();
                        preco_venda = prodPreco.getPrecovenda_20();
                        aliq_icms = 20;

                    } else if (jcb_icms.getSelectedItem().equals("21%")) {
                        preco_custo = prodPreco.getPrecocusto_21();
                        preco_venda = prodPreco.getPrecovenda_21();
                        aliq_icms = 21;

                    } else if (jcb_icms.getSelectedItem().equals("22%")) {
                        preco_custo = prodPreco.getPrecocusto_22();
                        preco_venda = prodPreco.getPrecovenda_22();
                        aliq_icms = 22;

                    } else if (jcb_icms.getSelectedItem().equals("17% (ALC)")) {
                        preco_custo = prodPreco.getPrecocusto_17_alc();
                        preco_venda = prodPreco.getPrecovenda_17_alc();
                        aliq_icms = 17;

                    } else if (jcb_icms.getSelectedItem().equals("17,5% (ALC)")) {
                        preco_custo = prodPreco.getPrecocusto_17_5_alc();
                        preco_venda = prodPreco.getPrecovenda_17_5_alc();
                        aliq_icms = 17.5;

                    } else if (jcb_icms.getSelectedItem().equals("18% (ALC)")) {
                        preco_custo = prodPreco.getPrecocusto_18_alc();
                        preco_venda = prodPreco.getPrecovenda_18_alc();
                        aliq_icms = 18;
                    }
                    escreva = Funcoes.AdicionaEspaco("" + Funcoes.formatoInteiro4Digitos(listaVersao.get(jcb_versao.getSelectedIndex() - 1).getId()), "D", 6).toUpperCase()
                            + Funcoes.AdicionaEspaco(listaVersao.get(jcb_versao.getSelectedIndex() - 1).getData_vigencia().replaceAll("\\D", ""), "D", 10).toUpperCase()
                            + Funcoes.AdicionaEspaco(p.getCodigo_ggrem(), "D", 17).toUpperCase()
                            + Funcoes.AdicionaEspaco(p.getRegistro(), "D", 15).toUpperCase()
                            + Funcoes.AdicionaEspaco(p.getEan1(), "D", 16).toUpperCase()
                            + Funcoes.AdicionaEspaco(p.getEan2(), "D", 16).toUpperCase()
                            + Funcoes.AdicionaEspaco(p.getEan3(), "D", 16).toUpperCase()
                            + Funcoes.AdicionaEspaco("" + p.getId(), "D", 13).toUpperCase()
                            + Funcoes.AdicionaEspaco(p.getProduto(), "D", 200).toUpperCase()
                            + Funcoes.AdicionaEspaco(p.getSubstancia(), "D", 600).toUpperCase()
                            + Funcoes.AdicionaEspaco(p.getApresentacao(), "D", 200).toUpperCase()
                            + Funcoes.AdicionaEspaco(p.getClasse_terapeutica(), "D", 200).toUpperCase()
                            + Funcoes.AdicionaEspaco(p.getCategoria().getNome() == null ? "" : p.getCategoria().getNome(), "D", 50).toUpperCase()
                            + Funcoes.AdicionaEspaco(p.getFabricante().getNome() == null ? "" : p.getFabricante().getNome(), "D", 120).toUpperCase()
                            + Funcoes.AdicionaEspaco(p.getTarja(), "D", 100).toUpperCase()
                            + Funcoes.AdicionaEspaco(p.getRegime_preco(), "D", 30).toUpperCase()
                            + Funcoes.AdicionaEspaco(p.getLista(), "D", 30).toUpperCase()
                            + Funcoes.AdicionaEspaco(p.getRestricao_hospitalar(), "D", 5).toUpperCase()
                            + Funcoes.AdicionaEspaco(p.getIcms_0(), "D", 5).toUpperCase()
                            + Funcoes.AdicionaEspaco("" + aliq_icms, "E", 12)
                            + Funcoes.AdicionaEspaco("" + preco_custo, "E", 12)
                            + Funcoes.AdicionaEspaco("" + preco_venda, "E", 12)
                            + Funcoes.AdicionaEspaco(prodPreco.getAtualizar().equals("S") ? "Sim" : "Nao", "E", 4).toUpperCase();

                    System.out.println(prodPreco.getId_produto() + " " + jcb_icms.getSelectedItem());
                    gravarArq.println(Funcoes.removeAcentos(escreva));
                }

            }
            gravarArq.flush();
            gravarArq.close();
            JOptionPane.showMessageDialog(null, "Arquivo gerado com sucesso!");
        }

    }
    //botoes

    private void gerarTXT() {
        try {
            gerar();
        } catch (Exception ex) {
            Logger.getLogger(TelaGerar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
